name: AngelJoy
favicon: null
layout_spectrum: 0.8497853463049978
typography_spectrum: 0.5140497849788517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.34048068593256176
  lightness: 0.8039864271413535
  saturation: 0.9539616021793336
  rhythmicContrast: 0.9211900646332651
purpose: []
