name: AngelJoy
favicon: null
layout_spectrum: 0.25539
typography_spectrum: 0.5140497849788517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7373a7'
    - '#85b1d8'
    - '#afc8dd'
    - '#908eb1'
  brandStrength: 0
  lightness: 1
  saturation: 0.9539616021793336
  rhythmicContrast: 0.5
purpose: []
